name: Laravel CI/CD with Docker Hub

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: laravel_test
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3
        ports:
          - 3306:3306

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2.12'
        extensions: mbstring, exif, pcntl, bcmath, pdo_mysql
        ini-values: post_max_size=256M, upload_max_filesize=256M, memory_limit=512M

    - name: Install dependencies
      run: composer install --prefer-dist --no-suggest --no-progress

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.11.0'

    - name: Install NPM dependencies
      run: npm install

    - name: Run NPM build
      run: npm run build 

    - name: Copy .env file
      run: cp .env.example .env    

    - name: Generate application key
      run: php artisan key:generate

    - name: Run migrations
      run: php artisan migrate --force

    - name: Run tests
      run: php artisan test --no-coverage
      continue-on-error: true

    - name: Run Code Quality Tools
      run: ./vendor/bin/phpstan analyse
      continue-on-error: true

  push-to-dockerhub:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/develop'

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and tag Docker image
      run: |
        docker build -t linalaroussi24/laravel-app:latest .
        docker tag linalaroussi24/laravel-app:latest linalaroussi24/laravel-app:${{ github.sha }}

    - name: Push Docker image to Docker Hub
      run: |
        docker push linalaroussi24/laravel-app:latest
        docker push linalaroussi24/laravel-app:${{ github.sha }}
